--商品類別
Insert into PRODUCTCLASS (PRO_CLASSID,PRO_CLASSNAME) values ('PT'||LPAD(to_char(PRODUCTCLASS_SEQ.NEXTVAL), 3, '0'),'羽球');
Insert into PRODUCTCLASS (PRO_CLASSID,PRO_CLASSNAME) values ('PT'||LPAD(to_char(PRODUCTCLASS_SEQ.NEXTVAL), 3, '0'),'跑步鞋');
Insert into PRODUCTCLASS (PRO_CLASSID,PRO_CLASSNAME) values ('PT'||LPAD(to_char(PRODUCTCLASS_SEQ.NEXTVAL), 3, '0'),'棒球');


--商品  母版Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),類別編號,'',           商品圖片,照片附檔名,商品規格,單價,庫存量,商品安全庫存量,商品詳述,商品狀態,商品評價,評價總人數);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT BASK ADV 經典鞋', null , null ,'US 9' , 4651 , 50 , 5 , 'EQT Bask ADV 系列的設計取材自中筒籃球鞋和 90 年代的 Equipment 跑鞋，採用彈性針織布料搭配麂皮細節，寬楦設計提供舒適腳感，鞋身三條線連接中底的三條線刻紋，重現 90 年代的經典造型。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','YUNG-2 經典鞋', null , null ,'US 7.5' , 4221 , 80 , 5 , 'EQT Bask ADV 系列的設計取材自中筒籃球鞋和 90 年代的 Equipment 跑鞋，採用彈性針織布料搭配麂皮細節，寬楦設計提供舒適腳感，鞋身三條線連接中底的三條線刻紋，重現 90 年代的經典造型。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT BASK ADV 經典鞋', null , null ,'US 8.5' , 4770 , 30 , 5 , 'Rivalry High 高筒鞋以 80 年代的經典籃球鞋為靈感，結合出色造型和現代舒適設計，鞋面採用柔軟無比的全粒面皮革，輕量 EVA 中底完美包覆雙腳。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','RIVALRY HIGH 經典鞋', null , null ,'US 8.5' , 3752 , 30 , 5 , 'Campus 採用質感奢華的鞋面和低筒籃球鞋設計，可說是數十年如一日的人氣街頭鞋款。此版本以嘻哈潮流和街頭元素為靈感，帶有寬版三條線圖案，展現煥然一新的 90 年代風格。材質為極為柔軟的磨砂革，搭配流線感橡膠鞋底和強化鞋頭。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','CAMPUS 經典鞋', null , null ,'US 8.5' , 2792 , 40 , 5 , '充滿創新元素的街頭單品。這款跑鞋風鞋款配有針織網布鞋面，可完美包覆雙腳，Boost 中底提供彈力舒適腳感，獨特的裝飾片為鞋款注入 NMD 經典風格。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','NMD_R0-NEW ADV 經典鞋', null , null ,'US 8.5' , 4761 , 60 , 5 , '設計大膽張揚，引領街頭時尚。此鞋款的側邊具有搶眼的刻紋結構，針織鞋面帶有不同的紋理效果，呈現獨特的仿舊質感，中底結構提供具支撐力的靈活腳感。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','NMD_R1 經典鞋', null , null ,'US 8.5' , 4761 , 100 , 5 , '設計大膽張揚，引領街頭時尚。此鞋款的側邊具有搶眼的刻紋結構，針織鞋面帶有不同的紋理效果，呈現獨特的仿舊質感，中底結構提供具支撐力的靈活腳感。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','PROPHERE 經典鞋', null , null ,'US 8.5' , 4871 , 100 , 5 , '此款休閒鞋採用全粒面皮革鞋面，搭配經典的橡膠貝殼型鞋頭，運用簡約線條與頂級材質，還原 adidas Superstar 的經典面貌。配置人字紋橡膠鞋底，後跟印有 Originals Logo。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','PROPHERE-NEW ADV 經典鞋', null , null ,'US 9.5' , 5611 , 100 , 5 , 'Yung 經典鞋以 90 年代的時尚潮流為靈感，設計大膽張揚，令人驚艷。採用網布、人造麂皮和磨砂革拼接而成，鞋型寬大厚實，復古味十足。輕量中底提供全天候舒適腳感。' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','SUPERSTAR FOUNDATION 休閒鞋', null , null ,'US 10.5' , 7899 , 30 , 5 , '穿上 Prophere，清新演繹街頭時尚。呈現誇張的結構比例和別緻的紋理質感，讓造型更加搶眼出色。鞋面採用堅固硬挺的編織材質，搭配柔韌中底。' , '上架中' , 321 ,71);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','YUNG-1 經典鞋', null , null ,'US 9.5' , 4778 , 40 , 5 , 'Prophere 獨特設計立體刻紋中底是 Prophere 的設計亮點' , '上架中' , 450 ,100);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','CAMPUS 經典鞋', null , null ,'US 11.5' , 3999 , 80 , 5 , '精準支撐針織鞋面提供局部支撐和自然貼合的舒適腳感' , '上架中' , 477 ,88);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','YUNG 經典鞋', null , null ,'US 10.5' , 3779 , 80 , 5 , 'Yung 1 鞋款以 90 年代後期的 adidas Falcon Dorf 跑鞋為靈感，以原創設計演繹復古風情，輪廓線條皆與 90 年代的經典鞋款相互呼應。' , '上架中' , 310 ,72);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT BASK ADV 經典鞋', null , null ,'US 9.5' , 5788 , 20 , 5 , '充滿創新元素的街頭單品。這款跑鞋風鞋款配有針織網布鞋面，可完美包覆雙腳，Boost 中底提供彈力舒適腳' , '上架中' , 566 ,130);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT BASK ADV 經典鞋', null , null ,'US 9.5' , 5788 , 20 , 5 , '設計取材自中筒籃球鞋和 90 年代的 Equipment 跑鞋，採用彈性針織布料搭配麂皮細' , '上架中' , 566 ,130);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT ADV-NEW 經典鞋', null , null ,'US 8.5' , 4777 , 20 , 5 , '設計取材自中筒籃球鞋和 90 年代的 Equipment 跑鞋，採用彈性針織布料搭配麂皮細節' , '上架中' , 430 ,88);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','YUNG 經典鞋', null , null ,'US 9.5' , 6667 , 23 , 5 , '搭配經典的橡膠貝殼型鞋頭，運用簡約線條與頂級材質，還原 adidas Superstar 的經典面貌。配置人字紋橡膠鞋底，後跟印有 Originals Logo' , '上架中' , 100 ,28);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','PROPHERE-TEX 經典鞋', null , null ,'US 8.5' , 5777 , 83 , 5 , '此鞋款的側邊具有搶眼的刻紋結構，針織鞋面帶有不同的紋理效果，呈現獨特的仿舊質感' , '上架中' , 176 ,44);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT SUPPORT MID ADV 經典鞋', null , null ,'US 10.5' , 6000 , 17 , 5 , '針織鞋面帶有不同的紋理效果，呈現獨特的仿舊質感' , '上架中' , 277 ,51);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT TEX MID ADV 經典鞋', null , null ,'US 10.5' , 5400 , 20 , 5 , '運用簡約線條與頂級材質，還原 adidas Superstar 的經典面貌。' , '上架中' , 388 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','YUNG MID 休閒鞋', null , null ,'US 10.5' , 8000 , 90 , 5 , '精準支撐針織鞋面提供局部支撐和自然貼合的舒適腳感' , '上架中' , 489 ,120);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','YUNG 1 休閒鞋', null , null ,'US 10.5' , 4670 , 90 , 5 , '搭配經典的橡膠貝殼型鞋頭，運用簡約線條與頂級材質' , '上架中' , 600 ,130);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','EQT BASK ADV 經典鞋', null , null ,'US 11.5' , 5433 , 10 , 5 , '設計大膽張揚，引領街頭時尚。此鞋款的側邊具有搶眼的刻紋結構，針織鞋面帶有不同的紋理效果' , '上架中' , 434 ,120);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','NMD_TS1 PRIMEKNIT 經典鞋', null , null ,'US 9.5' , 6700 , 20 , 5 , 'Prophere 獨特設計立體刻紋中底是 Prophere 的設計亮點' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','DEERUPT 經典鞋', null , null ,'US 7.5' , 3800 , 20 , 5 , '充滿創新元素的街頭單品。這款跑鞋風鞋款配有針織網布鞋面，可完美包覆雙腳' , '上架中' , 321 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','POD-S3.3 經典鞋', null , null ,'US 9.5' , 4400 , 60 , 5 , '充滿創新元素的街頭單品。這款跑鞋風鞋款配有針織網布鞋面，可完美包覆雙腳' , '上架中' , 544 ,120);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','SUPERSTAR 經典鞋', null , null ,'US 8.5' , 5700 , 10 , 5 , '獨特設計立體刻紋中底是 Prophere 的設計亮點' , '上架中' , 388 ,92);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','POD-X98.1 經典鞋', null , null ,'US 10.5' , 6800 , 51 , 5 , '設計大膽張揚，引領街頭時尚。此鞋款的側邊具有搶眼的刻紋結構，針織鞋面帶有不同的紋理效果' , '上架中' , 341 ,131);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','PROPHERE 經典鞋', null , null ,'US 9.5' , 4500 , 34 , 5 , '穿上 Prophere，清新演繹街頭時尚。呈現誇張的結構比例和別緻的紋理質感' , '上架中' , 131 ,87);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT002','NMD_R1 經典鞋', null , null ,'US 8.5' , 3777 , 20 , 5 , '設計大膽張揚，引領街頭時尚。此鞋款的側邊具有搶眼的刻紋結構，針織鞋面帶有不同的紋理效果' , '上架中' , 541 ,110);
--^羽球^
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','創意可攜式羽毛球網 PERFLY', null , null ,'單一尺寸' , 999 , 10 , 5 , '這款羽球網不只安裝容易，拆卸也很簡單，適合跟家人、朋友一起輕鬆享受打羽毛球的樂趣。本套裝備裡包含了2支球拍以及2顆羽毛球。 隨時隨地都能玩' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','初階款羽毛球套組 (拍*2 球*2、拍套) PERFLY', null , null ,'單一尺寸' , 299 , 30 , 5 , '這款球拍是通用型的，在打球過程中提供易操控性和舒適性. 非常適合在俱樂部里經常打球以提升自己' , '上架中' , 50 , 12);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','戶外用塑膠羽毛球 (3入) PERFLY', null , null ,'單一尺寸' , 129 , 40 , 5 , '本款耐用的羽毛球為鵝毛製，可於訓練時提供舒適感受' , '上架中' , 15 , 2);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','快速排汗羽毛球拍握把布 (3入) PERFLY 單一尺寸', null , null ,'單一尺寸' , 149 , 50 , 5 , '這款舒適、吸汗性佳的握把布，可提供良好的抓握感，讓你在球場享受更多樂趣' , '上架中' , 11 , 3);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','波浪型羽毛球拍握把布 PERFLY 單一尺寸', null , null ,'單一尺寸' , 89 , 20 , 5 , '本款握把布採單入的方式販售，可在您操控球拍時提供您良好的觸感其黏性可幫助您充分發揮' , '上架中' , 22 , 5);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','創意可攜式羽毛球網套組(2*拍+2*球) PERFLY', null , null ,'單一尺寸' , 1249 , 8 , 5 , '這款羽球網不只安裝容易，拆卸也很簡單，適合跟家人、朋友一起輕鬆享受打羽毛球的樂趣。本套組含有2支球拍以及2個羽毛球。' , '上架中' , 10 , 3);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','輕便可攜式羽球網 PERFLY', null , null ,'單一尺寸' , 1249 , 8 , 5 , '偶爾及經常從事網球運動者找尋可攜帶並保護兩支網球拍及整套網球裝備的包包' , '上架中' , 10 , 3);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','基本款羽毛球拍袋 PERFLY BL 720', null , null ,'單一尺寸' , 299 , 30 , 5 , '本款背包可容納兩支成人或青少年球拍，也是您攜帶所有網球裝備的最佳選擇' , '上架中' , 30 , 6);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','基本款球拍包 PERFLY', null , null ,'單一尺寸' , 199 , 10 , 5 , '本款球拍套可讓您攜帶球拍，並有效地保護球拍免受外部衝擊。' , '上架中' , 50 , 12);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','中階款羽毛球 (12入) PERFLY BSC ', null , null ,'單一尺寸' , 299 , 10 , 5 , '本款耐用的羽毛球為鵝毛製，可於訓練時提供舒適感受 (速度 77)是經常從事羽球運動的理想選擇！' , '上架中' , 50 , 12);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex Z-Force 2', null , null ,'4U G5' , 5980 , 15 , 0 , '小拍框型攻擊拍,全球最細的中管搭載TRI-VOLTAGE SYSTEM，瞬間絕殺' , '上架中' , 16 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex ASTROX 99', null , null ,'4U G5' , 5280 , 15 , 0 , '新世代攻擊拍,挑戰最短殺球距離極短' , '上架中' , 16 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex ASTROX 88S', null , null ,'4U G5' , 4980 , 15 , 0 , '暴力型攻擊拍,兼具平抽以及殺球' , '上架中' , 19 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex ASTROX 88D', null , null ,'4U G5' , 4980 , 15 , 0 , '全方位攻擊拍,兼具防守以及平抽球' , '上架中' , 19 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex DUORA Z-Strike', null , null ,'4U G5' , 5280 , 15 , 0 , '雙面刃,正面攻擊,反面破風,兼具殺球以及快速平抽球' , '上架中' , 17 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex DUORA 10 LT', null , null ,'4U G5' , 5280 , 15 , 0 , '輕量型的雙面刃,適合女性球友以及初學者' , '上架中' , 18 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex ARCSABER 11', null , null ,'4U G5' , 4680 , 15 , 0 , '準確瞄準,輕鬆駕馭攻擊' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex ARCSABER FB', null , null ,'4U G5' , 4980 , 15 , 0 , '全球最輕量的球拍,以速度逼退對手' , '上架中' , 19 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex NANORAY GlanZ', null , null ,'4U G5' , 4980 , 15 , 0 , '全方位球拍,以力距理論打造的Glanz加入REXIL FIBER新材料，將羽球送的更深更遠' , '上架中' , 19 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex POWER CUSHION AERUS 3', null , null ,'藍色' , 4700 , 15 , 0 , '頂級羽球鞋,提供更好的舒適以及最佳的包覆性' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex POWER CUSHION AERUS 3）', null , null ,'黑色' , 4700 , 15 , 0 , '頂級羽球鞋,提供更好的舒適以及最佳的包覆性' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex POWER CUSHION COMFORT Z', null , null ,'黑色' , 4600 , 15 , 0 , '稍微楦頭鞋型,舒適取向及良好的包覆性' , '上架中' , 19 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex POWER CUSHION 65Z', null , null ,'黑色' , 4600 , 15 , 0 , ' 楦頭腳型福音,,舒適取向及良好的包覆性' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex 超輕量型羽球鞋（黑）', null , null ,'黑色/桃紅' , 4300 , 15 , 0 , '最新型超輕量型羽球鞋,輕量之中,提供更好的避震效果' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex 超輕量型羽球鞋（桃紅）', null , null ,'桃紅' , 4300 , 15 , 0 , '最新型超輕量型羽球鞋,輕量之中,提供更好的避震效果' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Victor', null , null ,'1oz' , 600 , 15 , 0 , '比賽級鵝毛羽球,提供良好的飛行穩定性' , '上架中' , 18 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex AS-50', null , null ,'1oz' , 880 , 15 , 0 , 'BWF世界羽球聯賽指定用球' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex AS-30', null , null ,'1oz' , 780 , 15 , 0 , '頂級鵝毛,提供更高的耐用度及飛行的穩定度' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex AS-20', null , null ,'1oz' , 680 , 15 , 0 , '高級鵝毛,提供高品質的羽球' , '上架中' , 20 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values 
('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT001','Yonex ACB-TR', null , null ,'1oz' , 420 , 15 , 0 , '高級鴨毛,訓練專用用羽毛球' , '上架中' , 20 , 4);






--棒球
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','泡棉棒球 KIPSTA BA100', null , null ,'單一尺寸' , 69 , 10 , 5 , '想試試棒球嗎？我們的設計師已經開發了一款100％泡棉球，你可以安全地享受棒球樂趣。' , '上架中' , 30 , 7);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','橡膠泡棉球棒 KIPSTA Big Hit', null , null ,'單一尺寸' , 399 ,35 , 5 , '我們的設計師已經開發出這款質地柔軟的58.5cm球棒，幫助兒童安全的開始打棒球。' , '上架中' , 12 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','棒球組合 KIPSTA BA100', null , null ,'單一尺寸' , 799 ,35 , 5 , '適合每月兩次棒球訓練，本產品適合6歲以上的年輕運動者' , '上架中' , 13 , 4);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','吋木製棒球棒 KIPSTA BA150 30', null , null ,'單一尺寸' , 1199 ,5 , 2 , '這款木製球棒白樺木（梣木）有較大面積的最佳擊球點，幫助你擊球時產生更大的力道，讓你愛上棒球這項運動' , '上架中' , 53 , 15);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','打擊頭盔限量美國國旗配色特價', null , null ,'單一尺寸' , 1700 ,5 , 2 , '因為它的輕質及實用性，您絕對會愛上這頂頭盔。每個安全帽合三種頭圍尺寸。使用後端滾輪可自動調整。' , '上架中' , 33 , 7);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','全新2018zett進口加拿大紅楓木壘球棒', null , null ,'單一尺寸' , 2500 ,5 , 2 , '適合每月兩次棒球訓練，本產品適合6歲以上的年輕運動者' , '上架中' , 10 , 3);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','全新SA置球袋 EQ-3 黑色', null , null ,'單一尺寸' , 480 ,9 , 2 , '本款小型Artengo 背包可讓您攜帶所有的拍類運動基本裝備把所有的東西放在一起是完美的尺寸' , '上架中' , 13 , 3);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','羅林斯棒球手套內野工字', null , null ,'單一尺寸' , 3800 ,15 , 5 , '外手套與我們全系列的手套100%通用 使用時溫度能升高7°C 100%防水和100%防風100% 能夠收納在自身的小袋子裡，更加輕巧' , '上架中' , 30 ,7);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003',' BASEBALL側肩袋便利包', null , null ,'單一尺寸' , 890 ,15 , 5 , '本款小型Artengo 背包可讓您攜帶所有的拍類運動基本裝備把所有的東西放在一起是完美的尺寸' , '上架中' , 20 ,5);
Insert into PRODUCT (PRO_NO,PRO_CLASSID,PRO_NAME,PRO_PIC,PRO_PIC_EXT,PRO_FORMAT,PRO_BONUS,PRO_STOCK,PRO_SAFESTOCK,PRO_DETAILS,PRO_SHELVE,PRO_ALL_ASSESS,PRO_ALL_ASSESSMAN) values ('P'||LPAD(to_char(PRODUCT_SEQ.NEXTVAL), 3, '0'),'PT003','亞瑟士棒壘球橘色手感好 打擊手套', null , null ,'單一尺寸' , 990 ,15 , 5 , '季節限定的繽紛配色，鮮艷的底色搭配金屬光澤，抓住眾人目光。在手心處採用新式布紋，提升抓握能力' , '上架中' , 50 ,13);



--母版 訂單
Insert into ORD (ORD_NO,MEM_NO,ORD_DATE,ORD_DELDATE,ORD_STATUS,ORD_BACKDELDATE,ORD_AMOUNT,ORD_BACKAMOUNT) values (to_char(sysdate,'yyyymmdd')||'-'||LPAD(to_char(ORD_SEQ.NEXTVAL),6, '0'),'M001',CURRENT_TIMESTAMP,null,'待出貨',null,14035,0);
Insert into ORD (ORD_NO,MEM_NO,ORD_DATE,ORD_DELDATE,ORD_STATUS,ORD_BACKDELDATE,ORD_AMOUNT,ORD_BACKAMOUNT) values (to_char(sysdate,'yyyymmdd')||'-'||LPAD(to_char(ORD_SEQ.NEXTVAL),6, '0'),'M001',CURRENT_TIMESTAMP,null,'待出貨',null,6458,0);
Insert into ORD (ORD_NO,MEM_NO,ORD_DATE,ORD_DELDATE,ORD_STATUS,ORD_BACKDELDATE,ORD_AMOUNT,ORD_BACKAMOUNT) values (to_char(sysdate,'yyyymmdd')||'-'||LPAD(to_char(ORD_SEQ.NEXTVAL),6, '0'),'M001',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'完成',null,8379,0);
Insert into ORD (ORD_NO,MEM_NO,ORD_DATE,ORD_DELDATE,ORD_STATUS,ORD_BACKDELDATE,ORD_AMOUNT,ORD_BACKAMOUNT) values (to_char(sysdate,'yyyymmdd')||'-'||LPAD(to_char(ORD_SEQ.NEXTVAL),6, '0'),'M001',CURRENT_TIMESTAMP,null,'待出貨',null,13676,0);

Insert into ORD (ORD_NO,MEM_NO,ORD_DATE,ORD_DELDATE,ORD_STATUS,ORD_BACKDELDATE,ORD_AMOUNT,ORD_BACKAMOUNT) values (to_char(sysdate,'yyyymmdd')||'-'||LPAD(to_char(ORD_SEQ.NEXTVAL),6, '0'),'M002',CURRENT_TIMESTAMP,null,'待出貨',null,3985,0);
Insert into ORD (ORD_NO,MEM_NO,ORD_DATE,ORD_DELDATE,ORD_STATUS,ORD_BACKDELDATE,ORD_AMOUNT,ORD_BACKAMOUNT) values (to_char(sysdate,'yyyymmdd')||'-'||LPAD(to_char(ORD_SEQ.NEXTVAL),6, '0'),'M002',CURRENT_TIMESTAMP,null,'待出貨',null,0,0);

--母版 訂單明細
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000001','P001',4651,2);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000001','P031',999,3);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000001','P035',89,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000001','P036',1249,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000001','P035',199,2);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000002','P061',69,2);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000002','P065',1700,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000002','P002',4221,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000002','P062',399,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000003','P005',2792,3);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000004','P010',7899,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000004','P011',4778,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000004','P031',999,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000005','P030',3777,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000005','P033',139,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000005','P061',69,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000006','P006',4761,1);
Insert into ORDDETAILS(ORD_NO,PRO_NO,ORD_PROBONUNS,PRO_COUNT) values (to_char(sysdate,'yyyymmdd')||'-000006','P031',999,1);

commit;

